### ISSUE TITLE
Fails to build on Linux

### ISSUE THREAD

**Issue by robbyoconnor** [tomlandia/fuckr#69]
# Actual output
```
$ npm i  
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/rob/.nvm/versions/node/v5.12.0/bin/node" "/home/rob/.nvm/versions/node/v5.12.0/bin/npm" "i"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: appdmg@0.4.5
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rob/code/fuckr/npm-debug.log
```

# `npm-debug.txt`: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/rob/.nvm/versions/node/v5.12.0/bin/node',
1 verbose cli   '/home/rob/.nvm/versions/node/v5.12.0/bin/npm',
1 verbose cli   'i' ]
2 info using npm@3.8.6
3 info using node@v5.12.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData nw-builder
20 silly mapToRegistry name nw-builder
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'nw-builder',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   name: 'nw-builder',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://registry.npmjs.org/nw-builder
25 silly fetchNamedPackageData appdmg
26 silly mapToRegistry name appdmg
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'appdmg',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   name: 'appdmg',
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   spec: 'latest',
29 silly mapToRegistry   type: 'tag' }
30 silly mapToRegistry uri https://registry.npmjs.org/appdmg
31 silly fetchNamedPackageData archiver
32 silly mapToRegistry name archiver
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry data Result {
35 silly mapToRegistry   raw: 'archiver',
35 silly mapToRegistry   scope: null,
35 silly mapToRegistry   name: 'archiver',
35 silly mapToRegistry   rawSpec: '',
35 silly mapToRegistry   spec: 'latest',
35 silly mapToRegistry   type: 'tag' }
36 silly mapToRegistry uri https://registry.npmjs.org/archiver
37 verbose request uri https://registry.npmjs.org/nw-builder
38 verbose request no auth needed
39 info attempt registry request try #1 at 7:52:05 PM
40 verbose request using bearer token for auth
41 verbose request id 85fa0f4615ddcc88
42 verbose etag "CU31TR2BENWP55V0DUKKSO9VK"
43 http request GET https://registry.npmjs.org/nw-builder
44 verbose request uri https://registry.npmjs.org/appdmg
45 verbose request no auth needed
46 info attempt registry request try #1 at 7:52:05 PM
47 verbose request using bearer token for auth
48 verbose etag "530SX44NUTTT76AECHZE2PN6L"
49 http request GET https://registry.npmjs.org/appdmg
50 verbose request uri https://registry.npmjs.org/archiver
51 verbose request no auth needed
52 info attempt registry request try #1 at 7:52:05 PM
53 verbose request using bearer token for auth
54 verbose etag "A8CHCIGSYH7PL3WKIG0491SMO"
55 http request GET https://registry.npmjs.org/archiver
56 http 304 https://registry.npmjs.org/nw-builder
57 verbose headers { 'cache-control': 'max-age=300',
57 verbose headers   'accept-ranges': 'bytes',
57 verbose headers   date: 'Wed, 17 Aug 2016 23:52:01 GMT',
57 verbose headers   via: '1.1 varnish',
57 verbose headers   connection: 'keep-alive',
57 verbose headers   'x-served-by': 'cache-jfk8132-JFK',
57 verbose headers   'x-cache': 'MISS',
57 verbose headers   'x-cache-hits': '0',
57 verbose headers   'x-timer': 'S1471477921.880297,VS0,VE98',
57 verbose headers   vary: 'Accept-Encoding' }
58 silly get cb [ 304,
58 silly get   { 'cache-control': 'max-age=300',
58 silly get     'accept-ranges': 'bytes',
58 silly get     date: 'Wed, 17 Aug 2016 23:52:01 GMT',
58 silly get     via: '1.1 varnish',
58 silly get     connection: 'keep-alive',
58 silly get     'x-served-by': 'cache-jfk8132-JFK',
58 silly get     'x-cache': 'MISS',
58 silly get     'x-cache-hits': '0',
58 silly get     'x-timer': 'S1471477921.880297,VS0,VE98',
58 silly get     vary: 'Accept-Encoding' } ]
59 verbose etag https://registry.npmjs.org/nw-builder from cache
60 verbose get saving nw-builder to /home/rob/.npm/registry.npmjs.org/nw-builder/.cache.json
61 verbose correctMkdir /home/rob/.npm correctMkdir not in flight; initializing
62 http 304 https://registry.npmjs.org/appdmg
63 verbose headers { 'cache-control': 'max-age=300',
63 verbose headers   'accept-ranges': 'bytes',
63 verbose headers   date: 'Wed, 17 Aug 2016 23:52:01 GMT',
63 verbose headers   via: '1.1 varnish',
63 verbose headers   connection: 'keep-alive',
63 verbose headers   'x-served-by': 'cache-jfk8148-JFK',
63 verbose headers   'x-cache': 'MISS',
63 verbose headers   'x-cache-hits': '0',
63 verbose headers   'x-timer': 'S1471477921.886022,VS0,VE100',
63 verbose headers   vary: 'Accept-Encoding' }
64 silly get cb [ 304,
64 silly get   { 'cache-control': 'max-age=300',
64 silly get     'accept-ranges': 'bytes',
64 silly get     date: 'Wed, 17 Aug 2016 23:52:01 GMT',
64 silly get     via: '1.1 varnish',
64 silly get     connection: 'keep-alive',
64 silly get     'x-served-by': 'cache-jfk8148-JFK',
64 silly get     'x-cache': 'MISS',
64 silly get     'x-cache-hits': '0',
64 silly get     'x-timer': 'S1471477921.886022,VS0,VE100',
64 silly get     vary: 'Accept-Encoding' } ]
65 verbose etag https://registry.npmjs.org/appdmg from cache
66 verbose get saving appdmg to /home/rob/.npm/registry.npmjs.org/appdmg/.cache.json
67 verbose correctMkdir /home/rob/.npm correctMkdir already in flight; waiting
68 http 304 https://registry.npmjs.org/archiver
69 verbose headers { 'cache-control': 'max-age=300',
69 verbose headers   'accept-ranges': 'bytes',
69 verbose headers   date: 'Wed, 17 Aug 2016 23:52:02 GMT',
69 verbose headers   via: '1.1 varnish',
69 verbose headers   connection: 'keep-alive',
69 verbose headers   'x-served-by': 'cache-jfk8127-JFK',
69 verbose headers   'x-cache': 'MISS',
69 verbose headers   'x-cache-hits': '0',
69 verbose headers   'x-timer': 'S1471477921.893969,VS0,VE109',
69 verbose headers   vary: 'Accept-Encoding' }
70 silly get cb [ 304,
70 silly get   { 'cache-control': 'max-age=300',
70 silly get     'accept-ranges': 'bytes',
70 silly get     date: 'Wed, 17 Aug 2016 23:52:02 GMT',
70 silly get     via: '1.1 varnish',
70 silly get     connection: 'keep-alive',
70 silly get     'x-served-by': 'cache-jfk8127-JFK',
70 silly get     'x-cache': 'MISS',
70 silly get     'x-cache-hits': '0',
70 silly get     'x-timer': 'S1471477921.893969,VS0,VE109',
70 silly get     vary: 'Accept-Encoding' } ]
71 verbose etag https://registry.npmjs.org/archiver from cache
72 verbose get saving archiver to /home/rob/.npm/registry.npmjs.org/archiver/.cache.json
73 verbose correctMkdir /home/rob/.npm correctMkdir already in flight; waiting
74 silly resolveWithNewModule nw-builder@2.2.7 checking installable status
75 silly cache add args [ 'nw-builder@*', null ]
76 verbose cache add spec nw-builder@*
77 silly cache add parsed spec Result {
77 silly cache add   raw: 'nw-builder@*',
77 silly cache add   scope: null,
77 silly cache add   name: 'nw-builder',
77 silly cache add   rawSpec: '*',
77 silly cache add   spec: '*',
77 silly cache add   type: 'range' }
78 silly addNamed nw-builder@*
79 verbose addNamed "*" is a valid semver range for nw-builder
80 silly addNameRange { name: 'nw-builder', range: '*', hasData: false }
81 silly mapToRegistry name nw-builder
82 silly mapToRegistry using default registry
83 silly mapToRegistry registry https://registry.npmjs.org/
84 silly mapToRegistry data Result {
84 silly mapToRegistry   raw: 'nw-builder',
84 silly mapToRegistry   scope: null,
84 silly mapToRegistry   name: 'nw-builder',
84 silly mapToRegistry   rawSpec: '',
84 silly mapToRegistry   spec: 'latest',
84 silly mapToRegistry   type: 'tag' }
85 silly mapToRegistry uri https://registry.npmjs.org/nw-builder
86 verbose addNameRange registry:https://registry.npmjs.org/nw-builder not in flight; fetching
87 silly resolveWithNewModule appdmg@0.4.5 checking installable status
88 silly resolveWithNewModule archiver@1.0.1 checking installable status
89 silly cache add args [ 'archiver@*', null ]
90 verbose cache add spec archiver@*
91 silly cache add parsed spec Result {
91 silly cache add   raw: 'archiver@*',
91 silly cache add   scope: null,
91 silly cache add   name: 'archiver',
91 silly cache add   rawSpec: '*',
91 silly cache add   spec: '*',
91 silly cache add   type: 'range' }
92 silly addNamed archiver@*
93 verbose addNamed "*" is a valid semver range for archiver
94 silly addNameRange { name: 'archiver', range: '*', hasData: false }
95 silly mapToRegistry name archiver
96 silly mapToRegistry using default registry
97 silly mapToRegistry registry https://registry.npmjs.org/
98 silly mapToRegistry data Result {
98 silly mapToRegistry   raw: 'archiver',
98 silly mapToRegistry   scope: null,
98 silly mapToRegistry   name: 'archiver',
98 silly mapToRegistry   rawSpec: '',
98 silly mapToRegistry   spec: 'latest',
98 silly mapToRegistry   type: 'tag' }
99 silly mapToRegistry uri https://registry.npmjs.org/archiver
100 verbose addNameRange registry:https://registry.npmjs.org/archiver not in flight; fetching
101 verbose get https://registry.npmjs.org/archiver not expired, no request
102 silly addNameRange number 2 { name: 'archiver', range: '*', hasData: true }
103 silly addNameRange versions [ 'archiver',
103 silly addNameRange   [ '0.1.0',
103 silly addNameRange     '0.1.1',
103 silly addNameRange     '0.2.0',
103 silly addNameRange     '0.2.1',
103 silly addNameRange     '0.2.2',
103 silly addNameRange     '0.3.0',
103 silly addNameRange     '0.4.0',
103 silly addNameRange     '0.4.1',
103 silly addNameRange     '0.4.2',
103 silly addNameRange     '0.4.3',
103 silly addNameRange     '0.4.4',
103 silly addNameRange     '0.4.5',
103 silly addNameRange     '0.4.6',
103 silly addNameRange     '0.4.7',
103 silly addNameRange     '0.4.8',
103 silly addNameRange     '0.4.9',
103 silly addNameRange     '0.4.10',
103 silly addNameRange     '0.5.0-alpha',
103 silly addNameRange     '0.5.0',
103 silly addNameRange     '0.5.1',
103 silly addNameRange     '0.5.2',
103 silly addNameRange     '0.6.0',
103 silly addNameRange     '0.6.1',
103 silly addNameRange     '0.7.0',
103 silly addNameRange     '0.7.1',
103 silly addNameRange     '0.8.0',
103 silly addNameRange     '0.8.1',
103 silly addNameRange     '0.9.0',
103 silly addNameRange     '0.9.1',
103 silly addNameRange     '0.10.0-alpha',
103 silly addNameRange     '0.10.0',
103 silly addNameRange     '0.10.1',
103 silly addNameRange     '0.11.0-alpha',
103 silly addNameRange     '0.11.0',
103 silly addNameRange     '0.12.0',
103 silly addNameRange     '0.13.0',
103 silly addNameRange     '0.13.1',
103 silly addNameRange     '0.14.0',
103 silly addNameRange     '0.14.1',
103 silly addNameRange     '0.14.2',
103 silly addNameRange     '0.14.3',
103 silly addNameRange     '0.14.4',
103 silly addNameRange     '0.15.0-1',
103 silly addNameRange     '0.15.0',
103 silly addNameRange     '0.15.1',
103 silly addNameRange     '0.16.0',
103 silly addNameRange     '0.17.0',
103 silly addNameRange     '0.18.0',
103 silly addNameRange     '0.19.0',
103 silly addNameRange     '0.20.0',
103 silly addNameRange     '0.21.0',
103 silly addNameRange     '1.0.0',
103 silly addNameRange     '1.0.1' ] ]
104 silly addNamed archiver@1.0.1
105 verbose addNamed "1.0.1" is a plain semver version for archiver
106 verbose get https://registry.npmjs.org/nw-builder not expired, no request
107 silly addNameRange number 2 { name: 'nw-builder', range: '*', hasData: true }
108 silly addNameRange versions [ 'nw-builder',
108 silly addNameRange   [ '2.0.0',
108 silly addNameRange     '2.0.1',
108 silly addNameRange     '2.0.2',
108 silly addNameRange     '2.1.0',
108 silly addNameRange     '2.2.0',
108 silly addNameRange     '2.2.1',
108 silly addNameRange     '2.2.2',
108 silly addNameRange     '2.2.3',
108 silly addNameRange     '2.2.4',
108 silly addNameRange     '2.2.5',
108 silly addNameRange     '2.2.6',
108 silly addNameRange     '2.2.7' ] ]
109 silly addNamed nw-builder@2.2.7
110 verbose addNamed "2.2.7" is a plain semver version for nw-builder
111 silly cache afterAdd archiver@1.0.1
112 verbose afterAdd /home/rob/.npm/archiver/1.0.1/package/package.json not in flight; writing
113 verbose correctMkdir /home/rob/.npm correctMkdir not in flight; initializing
114 silly cache afterAdd nw-builder@2.2.7
115 verbose afterAdd /home/rob/.npm/nw-builder/2.2.7/package/package.json not in flight; writing
116 verbose correctMkdir /home/rob/.npm correctMkdir not in flight; initializing
117 verbose afterAdd /home/rob/.npm/archiver/1.0.1/package/package.json written
118 verbose afterAdd /home/rob/.npm/nw-builder/2.2.7/package/package.json written
119 silly rollbackFailedOptional Starting
120 silly rollbackFailedOptional Finishing
121 silly runTopLevelLifecycles Starting
122 silly runTopLevelLifecycles Finishing
123 silly install printInstalled
124 verbose stack Error: Unsupported platform for appdmg@0.4.5: wanted {"name":"appdmg","version":"0.4.5","license":"MIT","author":{"name":"Linus Unnebäck","email":"linus@folkdatorn.se"},"bin":{"appdmg":"bin/appdmg.js"},"main":"index.js","preferGlobal":true,"dependencies":{"async":"^1.4.2","cp-file":"^3.1.0","ds-store":"^0.1.5","execa":"^0.4.0","fs-temp":"^1.0.0","fs-xattr":"^0.1.14","image-size":"^0.5.0","is-my-json-valid":"^2.13.1","minimist":"^1.1.3","parse-color":"^1.0.0","repeat-string":"^1.5.4"},"engines":{"node":">=0.12"},"os":["darwin"],"repository":{"type":"git","url":"git+ssh://git@github.com/LinusU/node-appdmg.git"},"scripts":{"test":"standard && mocha -b"},"devDependencies":{"capture-window":"^0.1.3","looks-same":"^2.1.0","mocha":"^2.2.5","standard":"^7.0.1"},"gitHead":"da5ad4185188625a753ff79d822850d996973436","description":"Generate beautiful DMG-images for your OS X applications.","bugs":{"url":"https://github.com/LinusU/node-appdmg/issues"},"homepage":"https://github.com/LinusU/node-appdmg#readme","_id":"appdmg@0.4.5","_npmVersion":"3.8.9","_nodeVersion":"6.2.0","_npmUser":{"name":"linusu","email":"linus@folkdatorn.se"},"dist":{"shasum":"47a827865b8a0be48abb3522567e3493d2f1b838","tarball":"https://registry.npmjs.org/appdmg/-/appdmg-0.4.5.tgz"},"maintainers":[{"name":"cstruct","email":"albin@mattsson.io"},{"name":"linusu","email":"linus@folkdatorn.se"}],"_npmOperationalInternal":{"host":"packages-12-west.internal.npmjs.com","tmp":"tmp/appdmg-0.4.5.tgz_1463938029528_0.7859713893849403"},"directories":{},"_requested":{"raw":"appdmg@*","scope":null,"name":"appdmg","rawSpec":"*","spec":"*","type":"range"},"_spec":"appdmg@*","_where":"/home/rob/code/fuckr","_args":[["appdmg@*","/home/rob/code/fuckr"]],"readme":"ERROR: No README data found!"} (current: {"os":"linux","cpu":"x64"})
124 verbose stack     at checkPlatform (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/npm-install-checks/index.js:45:14)
124 verbose stack     at thenWarnEngineIssues (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/install/validate-args.js:41:5)
124 verbose stack     at /home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
124 verbose stack     at checkEngine (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/npm-install-checks/index.js:24:10)
124 verbose stack     at module.exports.isInstallable (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/install/validate-args.js:38:3)
124 verbose stack     at resolveWithNewModule (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/install/deps.js:462:12)
124 verbose stack     at /home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/install/deps.js:456:7
124 verbose stack     at /home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
124 verbose stack     at /home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
124 verbose stack     at addRequestedAndFinish (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
125 verbose pkgid appdmg@0.4.5
126 verbose cwd /home/rob/code/fuckr
127 error Linux 3.19.0-32-generic
128 error argv "/home/rob/.nvm/versions/node/v5.12.0/bin/node" "/home/rob/.nvm/versions/node/v5.12.0/bin/npm" "i"
129 error node v5.12.0
130 error npm  v3.8.6
131 error code EBADPLATFORM
132 error notsup Not compatible with your operating system or architecture: appdmg@0.4.5
133 error notsup Valid OS:    darwin
133 error notsup Valid Arch:  any
133 error notsup Actual OS:   linux
133 error notsup Actual Arch: x64
134 verbose exit [ 1, true ]

```

**Comment by tomlandia** [comment]
Sorry about the silly error, `appdmg` (the dmg package maker) has been moved to `optionalDependencies` as it only works on OS X. The build script already handled that.

**Comment by robbyoconnor** [comment]
Also, I found it hilarious about the issue # lol
